sudo: false

notifications:
  email: false

os: linux
dist: trusty
language: python
python:
  - 3.6


before_install:
  - pip install awscli
  - export PATH=$PATH:$HOME/.local/bin
  - export AWS_ACCESS_KEY_ID=$aws_access_key
  - export AWS_SECRET_ACCESS_KEY=$aws_secret_key


jobs:
  include:
    - stage: build_dry_image
      script: ./build/build_image --dry
    - stage: build_image
      script: ./build/build_image
    - stage: test_image
      script: ./test/test_image
